[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

#[programs.localnet]
#claws_effect = "6MDt7Xsgo7TAXmj41U6xdTgM1Yrou9Ksd49rLWJPxoiG"

[programs.devnet]
claws_effect = "11111111111111111111111111111111"
[registry]
url = "https://api.apr.dev"

[test]
startup_wait = 0
skip_local_validator = true
skip_test_scripts = true

[provider]
#cluster = "localnet"
cluster = 'devnet'
wallet = "~/.config/solana/id.json"

[scripts]
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
